//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Creating_With_Stored_Procedure.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class CustomerDataModelContainer : DbContext
    {
        public CustomerDataModelContainer()
            : base("name=CustomerDataModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<sp_user_list_Result> sp_user_list()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_user_list_Result>("sp_user_list");
        }
    }
}
